version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root # Set this value in .env file or directly
      - MYSQL_DATABASE=tp_foyers
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    depends_on:
      - mysqldb
    image: hadilibnhajfraj/backend-spring:1.0.0
    restart: on-failure
    env_file: ./.env
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tp_foyers?CreateDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": "root",  # Use correct environment variable
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: {}
